# general
DEVICE: 'cpu'


# searching
SEARCH_ONLY: False
RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2


# text split
REG_SEPARATORS: '[.!。！]'
CHUNK_SIZE: 500
CHUNK_OVERLAP: 0


# documents location for index/embedding
DATA_PATH: 'data/'


# vector database
DB_FAISS_PATH: 'vectorstore/db_faiss'


# sentence transformers model for vector search

# EMBEDDINGS_MODEL: 'sentence-transformers/all-MiniLM-L6-v2'
#EMBEDDINGS_MODEL: 'models/all-MiniLM-L6-v2'
EMBEDDINGS_MODEL: 'models/paraphrase-multilingual-MiniLM-L12-v2'

# LLM for generating answer

# MODEL_TYPE: 'mpt'
# MODEL_BIN_PATH: 'models/mpt-7b-instruct.ggmlv3.q8_0.bin'

# MODEL_TYPE: 'llama'
# MODEL_BIN_PATH: 'models/llama-2-7b-chat.Q2_K.gguf'
# MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q2_K.bin'
# MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q4_0.bin'
# MODEL_BIN_PATH: 'models/Llama2-chat-Chinese-50W-GGML.ggmlv3.q8_0.bin'

# MAX_NEW_TOKENS: 256
# TEMPERATURE: 0.01

MODEL_TYPE: 'chatglm'
MODEL_BIN_PATH: 'models/chatglm2-6b-int4'

MAX_NEW_TOKENS: 8192
TEMPERATURE: 0.01
